#################################################################
# Dockerfile for building a Hybris image with initialized content
# Prerequisites: running MySQL container
# the MySQL container is initialized and saved as well
# for Docker version: v1.3+
#################################################################

FROM nginx/alpine


# Set working directory
RUN mkdir -p $APP_HOME
