apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: requalize
    tier: db
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  # type: LoadBalancer
  ports:
    # the port that this service should serve on
  - port: 3306
  selector:
    app: requalize
    tier: db
